### ISSUE TITLE
Add support for prefers reduced motion

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyone#409]
As our goal is to create an accessible theme complying to WCAG level AAA,
and with the hopes that all transforms and animations has now been added, the theme should support 
_prefers reduced motion:_

https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

2.3.3 Animation from Interactions Level AAA
https://www.w3.org/TR/WCAG21/#animation-from-interactions

**Comment by aristath** [comment]
I don't think we have lots of animations or intense motion... However, if needed we can simply add the following to completely disable animations:

```css
@media (prefers-reduced-motion) {
  * {
    transition-delay: 0s !important;
    transition-duration: 0s !important;
  }
}
```
The use of `!important` here will be OK.
